### ISSUE TITLE
bug: align registry reachable logic with npm

### ISSUE THREAD

**Issue by literat** [privatenumber/npm-multi-publish#9]
Hi,

this package is great and I want to use it but I am ending up on VPN. Because I have multiple registries behind company VPN.

And I also wonder. Classic publish configuration with one registry and without this package works just fine even the registry is behind VPN. But when I use this package and configure multiple publish registries I got information that are unreachable.

If I have ani clue where the problem might be I could try to modify it myself. So could you give me any advice, please?

Thank you.

**Comment by privatenumber** [comment]
I don't quite understand the issue here, but `npm-multi-publsih` has support for registries behind VPNs. As a matter of fact, my personal use-case is to publish to multiple registries, each behind a different VPN.

Is it possible to upload a video of the problem you're encountering?
If you're getting an error, do you mind sharing it?

**Comment by literat** [comment]
We have 2 repositories, both using Nexus. Without this package publishing to first or second repository works just fine. Using this package I am stuck on "Retry" or "Exit".

<img width="1148" alt="Screenshot 2021-06-02 at 09 03 09" src="https://user-images.githubusercontent.com/2481010/120438317-7ff6a480-c381-11eb-9280-3ea7d02d07a5.png">

**Comment by privatenumber** [comment]
Maybe the prompt should be changed to "If it's behind a VPN, try enabling it" or something like that.

During that phase, make sure you're switching your VPN so `https://nexus3-3.sandbox.cdev` is reachable.

**Comment by privatenumber** [comment]
Glad you were able to resolve it.

I will leave this open since I think there's room for improvement in this package to better align with how npm interacts with the registry.


Some references for me:
- [npm ping](https://github.com/npm/cli/blob/73633e566661f38d78a61faa1ab43919dc5696e6/lib/ping.js)
- [npm publish](https://github.com/npm/cli/blob/73633e566661f38d78a61faa1ab43919dc5696e6/lib/publish.js)
- [npm-registry-fetch](https://github.com/npm/npm-registry-fetch)

**Comment by privatenumber** [comment]
Closed via https://github.com/privatenumber/npm-multi-publish/pull/11
